// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [arm64_const.rs]
pub const KS_ERR_ASM_ARM64_INVALIDOPERAND : u32 = 512;
pub const KS_ERR_ASM_ARM64_MISSINGFEATURE : u32 = 513;
pub const KS_ERR_ASM_ARM64_MNEMONICFAIL : u32 = 514;
