// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [arm_const.rs]
pub const KS_ERR_ASM_ARM_INVALIDOPERAND : u32 = 512;
pub const KS_ERR_ASM_ARM_MISSINGFEATURE : u32 = 513;
pub const KS_ERR_ASM_ARM_MNEMONICFAIL : u32 = 514;
