// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [hexagon_const.rs]
pub const KS_ERR_ASM_HEXAGON_INVALIDOPERAND : u32 = 512;
pub const KS_ERR_ASM_HEXAGON_MISSINGFEATURE : u32 = 513;
pub const KS_ERR_ASM_HEXAGON_MNEMONICFAIL : u32 = 514;
