// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [mips_const.rs]
pub const KS_ERR_ASM_MIPS_INVALIDOPERAND : u32 = 512;
pub const KS_ERR_ASM_MIPS_MISSINGFEATURE : u32 = 513;
pub const KS_ERR_ASM_MIPS_MNEMONICFAIL : u32 = 514;
