// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [systemz_const.rs]
pub const KS_ERR_ASM_SYSTEMZ_INVALIDOPERAND : u32 = 512;
pub const KS_ERR_ASM_SYSTEMZ_MISSINGFEATURE : u32 = 513;
pub const KS_ERR_ASM_SYSTEMZ_MNEMONICFAIL : u32 = 514;
