// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [msp430_const.js]
module.exports.ERR_ASM_MSP430_INVALIDOPERAND = 512
module.exports.ERR_ASM_MSP430_MISSINGFEATURE = 513
module.exports.ERR_ASM_MSP430_MNEMONICFAIL = 514
