// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [systemz_const.js]
module.exports.ERR_ASM_SYSTEMZ_INVALIDOPERAND = 512
module.exports.ERR_ASM_SYSTEMZ_MISSINGFEATURE = 513
module.exports.ERR_ASM_SYSTEMZ_MNEMONICFAIL = 514
