package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [arm64_const.go]

const (
	ERR_ASM_ARM64_INVALIDOPERAND Error = 512
	ERR_ASM_ARM64_MISSINGFEATURE Error = 513
	ERR_ASM_ARM64_MNEMONICFAIL Error = 514
)

