package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [hexagon_const.go]

const (
	ERR_ASM_HEXAGON_INVALIDOPERAND Error = 512
	ERR_ASM_HEXAGON_MISSINGFEATURE Error = 513
	ERR_ASM_HEXAGON_MNEMONICFAIL Error = 514
)

