package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [arm64_const.py]
const KS_ERR_ASM_ARM64_INVALIDOPERAND = 512
const KS_ERR_ASM_ARM64_MISSINGFEATURE = 513
const KS_ERR_ASM_ARM64_MNEMONICFAIL = 514
