package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [sparc_const.py]
const KS_ERR_ASM_SPARC_INVALIDOPERAND = 512
const KS_ERR_ASM_SPARC_MISSINGFEATURE = 513
const KS_ERR_ASM_SPARC_MNEMONICFAIL = 514
