package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [x86_const.py]
const KS_ERR_ASM_X86_INVALIDOPERAND = 512
const KS_ERR_ASM_X86_MISSINGFEATURE = 513
const KS_ERR_ASM_X86_MNEMONICFAIL = 514
