package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [systemz_const.py]
const KS_ERR_ASM_SYSTEMZ_INVALIDOPERAND = 512
const KS_ERR_ASM_SYSTEMZ_MISSINGFEATURE = 513
const KS_ERR_ASM_SYSTEMZ_MNEMONICFAIL = 514
