package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [hexagon_const.py]
const KS_ERR_ASM_HEXAGON_INVALIDOPERAND = 512
const KS_ERR_ASM_HEXAGON_MISSINGFEATURE = 513
const KS_ERR_ASM_HEXAGON_MNEMONICFAIL = 514
