package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [riscv_const.go]

const (
	ERR_ASM_RISCV_INVALIDOPERAND Error = 512
	ERR_ASM_RISCV_MISSINGFEATURE Error = 513
	ERR_ASM_RISCV_MNEMONICFAIL Error = 514
)

