package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [sparc_const.go]

const (
	ERR_ASM_SPARC_INVALIDOPERAND Error = 512
	ERR_ASM_SPARC_MISSINGFEATURE Error = 513
	ERR_ASM_SPARC_MNEMONICFAIL Error = 514
)

