package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [systemz_const.go]

const (
	ERR_ASM_SYSTEMZ_INVALIDOPERAND Error = 512
	ERR_ASM_SYSTEMZ_MISSINGFEATURE Error = 513
	ERR_ASM_SYSTEMZ_MNEMONICFAIL Error = 514
)

