package keystone
// For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [x86_const.go]

const (
	ERR_ASM_X86_INVALIDOPERAND Error = 512
	ERR_ASM_X86_MISSINGFEATURE Error = 513
	ERR_ASM_X86_MNEMONICFAIL Error = 514
)

