# For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [evm_const.rb]

module Keystone
	KS_ERR_ASM_EVM_INVALIDOPERAND = 512
	KS_ERR_ASM_EVM_MISSINGFEATURE = 513
	KS_ERR_ASM_EVM_MNEMONICFAIL = 514
end