# For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [msp430_const.rb]

module Keystone
	KS_ERR_ASM_MSP430_INVALIDOPERAND = 512
	KS_ERR_ASM_MSP430_MISSINGFEATURE = 513
	KS_ERR_ASM_MSP430_MNEMONICFAIL = 514
end