# For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [ppc_const.rb]

module Keystone
	KS_ERR_ASM_PPC_INVALIDOPERAND = 512
	KS_ERR_ASM_PPC_MISSINGFEATURE = 513
	KS_ERR_ASM_PPC_MNEMONICFAIL = 514
end