# For Keystone Engine. AUTO-GENERATED FILE, DO NOT EDIT [riscv.h_const.rb]

module Keystone
	KS_ERR_ASM_RISCV_INVALIDOPERAND = 512
	KS_ERR_ASM_RISCV_MISSINGFEATURE = 513
	KS_ERR_ASM_RISCV_MNEMONICFAIL = 514
end